### ISSUE TITLE
module 'tensorflow' has no attribute 'get_default_session'

### ISSUE THREAD

**Issue by sidvenkat1988** [kr-sundaram/pyrack#1]
I am getting this error while I try to detect the objects.

**Comment by sree11rd** [comment]
pip install tensorflow==1.14.0

**Comment by sree11rd** [comment]
Hey @sidvenkat1988, either:

1) pip install tensorflow==1.14.0

or:

2) import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

**Comment by sidvenkat1988** [comment]
Thanks @sree11rd
